### ISSUE TITLE
always_populate_raw_post_data is set to 0, although php.ini indicates a default of -1

### ISSUE THREAD

**Issue by gnotaras** [iuscommunity-pkg/php56u#19] opened 2016-07-16 10:35 UTC
Hi,

php.ini [indicates](https://github.com/iuscommunity-pkg/php56u/blob/master/SOURCES/php.ini#L705) that the default value of `always_populate_raw_post_data` is `-1`.

When checking phpinfo, it seems it is set to `0` instead:

```
~]# php -i | grep always_populate_raw_post_data
always_populate_raw_post_data => 0 => 0
```

Maybe this setting should be explicitly set to `-1` in php.ini.

I found out about this while trying to experiment with php56u from IUS and a web application, which detected this inconsistency.

Thank you in advance for looking into it.

**Comment by carlwgeorge** [comment] 2016-08-10 14:52
Since I think this is working as intended, I'm going to close this out.

**Closed by carlwgeorge** 2016-08-10 14:52 UTC

**Comment by gnotaras** [comment] 2016-08-10 16:22
Hi @carlwgeorge 

Somehow I missed the notification about your reply. I'm sorry about that.

I also did some research about it and found the following deprecation notice [here](https://secure.php.net/manual/en/migration56.deprecated.php#migration56.deprecated.raw-post-data):

```
always_populate_raw_post_data will now generate an E_DEPRECATED error when
$HTTP_RAW_POST_DATA is populated. New code should use php://input instead of
$HTTP_RAW_POST_DATA, which will be removed in a future release. You can opt in for the new
behaviour (in which $HTTP_RAW_POST_DATA is never defined hence no E_DEPRECATED error will
be generated) by setting always_populate_raw_post_data to -1. 
```

From what I understand, opting in for the new functionality requires setting this option to `-1`. If `-1` is also the internal default value, then shouldn't it result in a value of `0` at runtime, regardless of either explicitly setting it to `-1` or leaving it commented out in `php.ini`?

However, in practice I get the following results.

If I comment it out in `php.ini`, then I get the following:

```
~]# php -i | grep always_populate_raw_post_data
always_populate_raw_post_data => 0 => 0
```

If I explicitly set it to `-1` in `php.ini` I get the following result:

```
~]# php -i | grep always_populate_raw_post_data
always_populate_raw_post_data => -1 => -1
```

Maybe I'm not interpreting it correctly right now or maybe the documentation does not clarify it very well. Please, do as you see fit. Leaving it commented out is definitely not wrong.

**Comment by carlwgeorge** [comment] 2016-08-17 15:14
I certainly agree that the documentation doesn't clarify this well.  I'm interpreting it as -1 and 0 are basically the same ("do not populate" vs "never populate").  Regardless it should be a moot point since the setting is deprecated in PHP 5.6 (and removed in PHP 7.0).

**Comment by kustodian** [comment] 2016-08-30 18:40
The issue is that the commented setting in `php.ini` is incorrect. It is set to:
```
;always_populate_raw_post_data = -1
```
Which suggests that the default value is `-1`, but it's not, the actual default is `0`. Could you please change the commented value in `php.ini` to `0`, so it's displaying the correct value, since currently it is misleading.

If you ask me it's stupid how PHP implemented this warning, because it's reporting the error when the variable is populated, not used, but the commented value in `php.ini` should be correct. This is also a very small change since you are only change the comment.

**Comment by carlwgeorge** [comment] 2016-08-30 20:07
The general problem with situations like this is that it could be fixed several ways.

* fix the documentation (configuration comment) to match the runtime default
* fix the runtime default to match the documentation (configuration comment)

From the packaging perspective, if we change a configuration file (even just a single character) it will result in `php.ini.rpmnew` files for every user that has local customizations.  I am hesitant to do that until we get clarification from upstream to avoid repeat work.  Please [file a bug upstream](https://bugs.php.net) and share the link here.  Once upstream takes a stand will will follow suit.
